/**
 * INDEPENDENT verification in a browser, in Node, or anywhere else JavaScript runs.
 *
 * The same arithmetic as `orilife.verify` on the Python side, down to the same number — checked
 * against a vector set generated by the very code running on the server.
 *
 * Why a separate JavaScript build: if the only way to check a record were to run Python, a buyer
 * holding a phone could not check anything, and "anyone can verify" would quietly become "anyone
 * with a computer who knows how to install Python can verify". A static web page that embeds this
 * file is enough for a stranger to check for themselves.
 *
 * No network, no dependencies, no state.
 */
import { blake2b, sha256, sha3_256 } from './hash.js';

export const RECORD_VERSION = 2;
export const HASH_ALGORITHM = 'sha3-256';
export const HASH_ALGORITHM_LEGACY = 'blake2b-256';

const GEOHASH_ALPHABET = '0123456789bcdefghjkmnpqrstuvwxyz';
// Crockford base32: drops I, L, O and U so that a code read by eye cannot be confused with 1 and 0.
const CROCKFORD_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

// The table of ALLOWED algorithms. Anything outside it verifies as false and does NOT fall back to
// a default — falling back would open the very door that letting a record declare its own algorithm
// was meant to close.
const HASHERS = {
  'sha3-256': (bytes) => sha3_256(bytes),
  'blake2b-256': (bytes) => blake2b(bytes, 32),
};

/**
 * Standard geohash (Niemeyer). Seven characters ≈ a 150 m cell: enough to say "which area", not
 * enough to point at one trunk.
 */
export function geohash(lat, lon, precision = 7) {
  const latRange = [-90, 90];
  const lonRange = [-180, 180];
  let out = '';
  let bit = 0;
  let acc = 0;
  let even = true;
  while (out.length < precision) {
    if (even) {
      const mid = (lonRange[0] + lonRange[1]) / 2;
      if (lon > mid) { acc |= 1 << (4 - bit); lonRange[0] = mid; } else { lonRange[1] = mid; }
    } else {
      const mid = (latRange[0] + latRange[1]) / 2;
      if (lat > mid) { acc |= 1 << (4 - bit); latRange[0] = mid; } else { latRange[1] = mid; }
    }
    even = !even;
    if (bit < 4) { bit += 1; } else { out += GEOHASH_ALPHABET[acc]; bit = 0; acc = 0; }
  }
  return out;
}

function crockford(hexDigest, nChars) {
  let number = BigInt(`0x${hexDigest}`);
  const totalBits = BigInt(hexDigest.length * 4);
  let out = '';
  for (let i = 0; i < nChars; i += 1) {
    const shift = totalBits - 5n * BigInt(i + 1);
    const index = shift < 0n ? Number((number << -shift) & 0x1fn) : Number((number >> shift) & 0x1fn);
    out += CROCKFORD_ALPHABET[index];
  }
  return out;
}

/**
 * The stable public code of one individual: `ORI-<geohash7>-<8 characters>`.
 *
 * Use it to CROSS-CHECK: take the code printed on the slip, call this with the identifier the
 * server returned, and both sides must produce the same string. A mismatch means one of the two
 * ends changed.
 */
export function entityCode(entityId, gps = null) {
  const digest = blake2b(entityId, 8);
  const suffix = crockford(digest, 8);
  const cell = (gps && gps.length === 2 && gps[0] != null && gps[1] != null)
    ? geohash(Number(gps[0]), Number(gps[1]), 7)
    : '0000000';
  return `ORI-${cell}-${suffix}`;
}

/**
 * Compare keys by Unicode CODE POINT, not by UTF-16 unit.
 *
 * `Array.prototype.sort()` compares UTF-16 units by default, which differs from Python outside the
 * basic multilingual plane. Every key in today's records is ASCII, so both ways agree — but one new
 * key with an unusual character would shift the hash for reasons nobody could explain, so the
 * comparison is pinned down here.
 */
function byCodePoint(a, b) {
  const ca = [...a];
  const cb = [...b];
  for (let i = 0; i < Math.min(ca.length, cb.length); i += 1) {
    const d = ca[i].codePointAt(0) - cb[i].codePointAt(0);
    if (d !== 0) return d;
  }
  return ca.length - cb.length;
}

/**
 * DETERMINISTIC serialisation: sorted keys, no stray whitespace, non-ASCII text left as it is.
 *
 * All three are mandatory. A different key order, one space after a colon, or a Vietnamese
 * character turned into `\\uXXXX` — each on its own shifts the hash while the content is
 * identical, and whoever is verifying will conclude the record was tampered with rather than
 * serialised differently.
 */
export function canonicalJson(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`;
  const keys = Object.keys(value).filter((k) => value[k] !== undefined).sort(byCodePoint);
  return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalJson(value[k])}`).join(',')}}`;
}

const utf8 = (s) => new TextEncoder().encode(s);

export function hashBytes(bytes, algorithm = HASH_ALGORITHM) {
  const fn = HASHERS[String(algorithm || '').trim().toLowerCase()];
  if (!fn) throw new RangeError(`unsupported hash algorithm: ${algorithm}`);
  return fn(bytes);
}

/**
 * The hash algorithm OF THIS RECORD — read from the record, never guessed from a date. When an old
 * record does not declare one, `v<=1` means blake2b; a missing `v` also counts as v=1, because the
 * older a record is the more fields it lacks, so the default has to lean towards the old side for
 * history to stay verifiable.
 */
export function recordAlgorithm(record) {
  const declared = String((record && record.hash_alg) || '').trim().toLowerCase();
  if (declared) return declared;
  const version = Number((record && record.v) || 1);
  return Number.isFinite(version) && version <= 1 ? HASH_ALGORITHM_LEGACY : HASH_ALGORITHM;
}

/** Hash a record with the CURRENT algorithm. To CHECK an existing record, use `verifyRecord`. */
export function recordHash(record) {
  return hashBytes(utf8(canonicalJson(record)), HASH_ALGORITHM);
}

/**
 * Is this record really the thing that hashed to `expectedHash`?
 *
 * Feed it the record JSON pulled from storage and the number read on a block explorer, get back
 * true or false. There is no downgrade path: the `hash_alg` key sits INSIDE what gets hashed, so
 * editing it to force a weaker algorithm has already changed the content, and the hash no longer
 * matches.
 */
export function verifyRecord(record, expectedHash) {
  if (!record || typeof record !== 'object' || typeof expectedHash !== 'string' || !expectedHash) {
    return false;
  }
  try {
    return hashBytes(utf8(canonicalJson(record)), recordAlgorithm(record)) === expectedHash.trim().toLowerCase();
  } catch {
    return false;
  }
}

/** SHA-256 of a block of bytes — to compare against the `sha256` field inside a record. */
export async function sha256Of(bytes) { return sha256(bytes); }

/**
 * Which required fields are absent. It exists to separate two very different cases: a COMPLETE
 * record whose hash does not match (suspect tampering) and a record MISSING fields (far more often
 * an incomplete download or the wrong shard).
 */
export function missingFields(record, required = ['v', 'code', 'gps', 'enrolled_at', 'images']) {
  return required.filter((k) => !(record && k in record));
}

/** A one-line summary for tools and agents: what this record says, and whether it matches. */
export function summarize(record, expectedHash = null) {
  const images = (record && record.images) || [];
  return {
    code: record && record.code,
    version: record && record.v,
    algorithm: recordAlgorithm(record),
    enrolledAt: record && record.enrolled_at,
    nImages: Array.isArray(images) ? images.length : 0,
    has3d: Boolean(record && record.model3d),
    missingFields: missingFields(record),
    hashMatches: expectedHash ? verifyRecord(record, expectedHash) : null,
  };
}
